# Tên của workflow
name: Build LinhTienPlugin with Gradle

# Điều kiện kích hoạt
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Các công việc
jobs:
  build:
    # Sử dụng máy ảo Ubuntu phiên bản mới nhất
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Tải mã nguồn từ repository của bạn vào máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt môi trường Java JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # Bước 3: Thiết lập Gradle (thay thế cho Maven)
      # Bước này sẽ tự động cache các dependency của Gradle để build nhanh hơn
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Bước 4: Cấp quyền thực thi cho Gradle Wrapper
      # Đây là bước quan trọng để action có thể chạy lệnh build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Bước 5: Build project bằng Gradle Wrapper
      # Thay thế hoàn toàn lệnh 'mvn'
      - name: Build with Gradle
        run: ./gradlew build

      # Bước 6: Tải lên artifact (file .jar đã build)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LinhTienPluginVipBoRo-Build
          # File jar của Gradle nằm trong thư mục build/libs/
          path: build/libs/*.jar